export interface ProductColor {
  name: string;
  hex: string;
}

export interface ProductSize {
  key: string;
  label: string;
  cm: string;
  priceAdd: number;
}

export interface Product {
  id: number;
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  price: number;
  description: string;
  longDescription: string;
  features: string[];
  colors: ProductColor[];
  sizes: ProductSize[];
  tags: string[];
  badge?: string;
  emoji: string;
  glowColor: string;
  material: string;
  warranty: string;
  deliveryDays: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  isNew?: boolean;
  isBestSeller?: boolean;
}

export const PRODUCT_SIZES: ProductSize[] = [
  { key: "xs", label: "XS", cm: "30cm", priceAdd: 0 },
  { key: "s",  label: "S",  cm: "50cm", priceAdd: 800 },
  { key: "m",  label: "M",  cm: "70cm", priceAdd: 1800 },
  { key: "l",  label: "L",  cm: "100cm", priceAdd: 3200 },
  { key: "xl", label: "XL", cm: "150cm", priceAdd: 6000 },
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: "bi-guzellik-yap-kendine",
    name: "Bi Güzellik Yap Kendine",
    category: "Güzellik & Kuaför",
    categorySlug: "guzellik",
    price: 5985,
    description: "Güzellik salonlarının gözdesi. Selfie köşenizin vazgeçilmezi.",
    longDescription: "Güzellik salonları, kuaförler ve spa merkezleri için tasarlanmış bu neon tabela, mekanınıza premium bir hava katarken müşterilerinize anılarını ölümsüzleştirme fırsatı sunar. Sosyal medya paylaşımları için mükemmel bir arka plan oluşturur.",
    features: ["UV korumalı", "Ses yalıtımlı transformatör", "Duvar montajı dahil", "Uzaktan kumanda"],
    colors: [
      { name: "Neon Pembe", hex: "#FF00C8" },
      { name: "Mor", hex: "#9B5CFF" },
      { name: "Beyaz", hex: "#FFFFFF" },
      { name: "Altın", hex: "#FFD700" },
    ],
    sizes: PRODUCT_SIZES,
    tags: ["güzellik", "kuaför", "salon", "selfie"],
    badge: "Çok Satan",
    emoji: "✨",
    glowColor: "#FF00C8",
    material: "LED Neon Flex + Akrilik Panel",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.9,
    reviewCount: 128,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 2,
    slug: "daima-ask-ile",
    name: "Daima Aşk İle",
    category: "Özel Günler",
    categorySlug: "ozel-gun",
    price: 5990,
    description: "Sevdiklerinize sonsuz bir hediye. Evlilik teklifi, yıl dönümü, doğum günü.",
    longDescription: "Sevgilinize, eşinize ya da kendinize en özel hediyeyi verin. 'Daima Aşk İle' tabelası, aşkınızı ve bağlılığınızı kalıcı bir ışık ile ifade eder. Her gece odanızı romantik bir atmosfere büründürür.",
    features: ["Romantik ışık efekti", "Dimmer dahil", "Kişiselleştirme seçeneği", "Hediye kutusu"],
    colors: [
      { name: "Neon Pembe", hex: "#FF00C8" },
      { name: "Kırmızı", hex: "#FF3131" },
      { name: "Mor", hex: "#9B5CFF" },
      { name: "Beyaz", hex: "#FFFFFF" },
    ],
    sizes: PRODUCT_SIZES,
    tags: ["aşk", "hediye", "yıl dönümü", "evlilik"],
    badge: "Yeni",
    emoji: "❤️",
    glowColor: "#FF00C8",
    material: "LED Neon Flex + Akrilik Panel",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 5.0,
    reviewCount: 89,
    inStock: true,
    isNew: true,
  },
  {
    id: 3,
    slug: "hosgeldiniz",
    name: "Hoşgeldiniz",
    category: "İşletme",
    categorySlug: "isletme",
    price: 5680,
    description: "Müşterilerinizi sıcak bir ışıkla karşılayın. Her işletmeye uygun.",
    longDescription: "İşletmenizin girişine yerleştireceğiniz 'Hoşgeldiniz' tabelası, müşterilerinizin ilk izlenimi için mükemmel bir karşılama noktası oluşturur. Restoranlar, kafeler, oteller ve her türlü ticari mekana uygundur.",
    features: ["Giriş montajına uygun", "IP65 su geçirmezlik seçeneği", "Çoklu renk seçeneği", "Kurulum desteği"],
    colors: [
      { name: "Neon Mavi", hex: "#00E5FF" },
      { name: "Neon Yeşil", hex: "#39FF14" },
      { name: "Beyaz", hex: "#FFFFFF" },
      { name: "Turuncu", hex: "#FF7A00" },
    ],
    sizes: PRODUCT_SIZES,
    tags: ["işletme", "giriş", "karşılama", "tabela"],
    badge: "Popüler",
    emoji: "👋",
    glowColor: "#00E5FF",
    material: "LED Neon Flex + Akrilik Panel",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.8,
    reviewCount: 214,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 4,
    slug: "neon-cerceveli-ayna",
    name: "Neon Çerçeveli Ayna",
    category: "Ev Dekorasyon",
    categorySlug: "ev",
    price: 19950,
    description: "Odanızı bir sanat galerisine dönüştürün. Boy aynası + neon çerçeve.",
    longDescription: "Lüks bir tasarım şaheseri olan neon çerçeveli boy aynası, hem işlevsel hem de dekoratif bir ürün. Yatakodası, giyinme odası veya oturma odanıza premium bir dokunuş katar. Instagramın en çok paylaşılan dekor ürünü.",
    features: ["Full-length boy aynası", "Premium ayna kalitesi", "LED şerit entegreli çerçeve", "Ayarlanabilir parlaklık"],
    colors: [
      { name: "Mor", hex: "#9B5CFF" },
      { name: "Neon Pembe", hex: "#FF00C8" },
      { name: "Neon Mavi", hex: "#00E5FF" },
      { name: "Beyaz", hex: "#FFFFFF" },
    ],
    sizes: [
      { key: "s", label: "S", cm: "60×120cm", priceAdd: 0 },
      { key: "m", label: "M", cm: "70×150cm", priceAdd: 3000 },
      { key: "l", label: "L", cm: "80×180cm", priceAdd: 6000 },
    ],
    tags: ["ayna", "ev dekorasyon", "lüks", "premium"],
    badge: "Premium",
    emoji: "🪞",
    glowColor: "#9B5CFF",
    material: "Ayna + LED Neon Flex + Metal Çerçeve",
    warranty: "2 Yıl",
    deliveryDays: "10-14 iş günü",
    rating: 4.9,
    reviewCount: 67,
    inStock: true,
  },
  {
    id: 5,
    slug: "tac-neon-tabela",
    name: "Taç Neon Tabela",
    category: "Kişisel",
    categorySlug: "kisisel",
    price: 3960,
    description: "Kraliçenizin tahtına layık bir tabela. Genç odası, makyaj masası.",
    longDescription: "Taç tasarımlı neon tabelamız, genç kız odaları, makyaj köşeleri ve güzellik alanları için harika bir seçim. Kendinizi bir prenses gibi hissettirecek bu ışıklı süsleme, fotoğraflarınızı da parlatacak.",
    features: ["Asimetrik taç tasarımı", "Kompakt boyut", "Kolay asma aparatı", "Düşük enerji tüketimi"],
    colors: [
      { name: "Altın", hex: "#FFD700" },
      { name: "Neon Pembe", hex: "#FF00C8" },
      { name: "Mor", hex: "#9B5CFF" },
      { name: "Beyaz", hex: "#FFFFFF" },
    ],
    sizes: PRODUCT_SIZES.slice(0, 4),
    tags: ["taç", "kişisel", "genç odası", "dekorasyon"],
    badge: "Çok Satan",
    emoji: "👑",
    glowColor: "#FFD700",
    material: "LED Neon Flex + Şeffaf Akrilik",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 6,
    slug: "open-24-7",
    name: "OPEN 24/7",
    category: "İşletme",
    categorySlug: "isletme",
    price: 4250,
    description: "7/24 açık olduğunuzu ışıklı bir şekilde duyurun.",
    longDescription: "Eczane, market, kebapçı veya 24 saat hizmet veren her işletme için vazgeçilmez bir tabela. Müşterileriniz uzaktan da görebilsin diye yüksek parlaklıkta üretilir.",
    features: ["Yüksek parlaklık", "İç/dış mekan kullanımı", "IP65 su geçirmezlik", "Güneş ışığında görünür"],
    colors: [
      { name: "Neon Yeşil", hex: "#39FF14" },
      { name: "Kırmızı", hex: "#FF3131" },
      { name: "Beyaz", hex: "#FFFFFF" },
      { name: "Neon Mavi", hex: "#00E5FF" },
    ],
    sizes: PRODUCT_SIZES,
    tags: ["açık", "işletme", "dış mekan", "24 saat"],
    emoji: "🟢",
    glowColor: "#39FF14",
    material: "LED Neon Flex + Alüminyum Profil",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.8,
    reviewCount: 203,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 7,
    slug: "coffee-shop",
    name: "Coffee Shop ☕",
    category: "Kafe",
    categorySlug: "kafe",
    price: 4800,
    description: "Kafenizin ambiyansını bir üst seviyeye taşıyın.",
    longDescription: "Kahve aşıklarının mekanı olan kafelere özel tasarlanmış bu tabela, sıcak ve davetkar bir atmosfer yaratır. Fotoğrafçıların ve Instagram'ın en sevdiği kafe köşelerinden biri haline getirmek için mükemmel.",
    features: ["Sıcak turuncu ışık tonu", "Ahşap panel seçeneği", "Duvar ve tavan montajı", "Dimmer dahil"],
    colors: [
      { name: "Turuncu", hex: "#FF7A00" },
      { name: "Altın", hex: "#FFD700" },
      { name: "Beyaz Sıcak", hex: "#FFF5E0" },
      { name: "Neon Pembe", hex: "#FF00C8" },
    ],
    sizes: PRODUCT_SIZES,
    tags: ["kafe", "kahve", "coffee", "barista"],
    badge: "Popüler",
    emoji: "☕",
    glowColor: "#FF7A00",
    material: "LED Neon Flex + Ahşap/Akrilik Panel",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.9,
    reviewCount: 178,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 8,
    slug: "dream-big",
    name: "Dream Big",
    category: "Kişisel",
    categorySlug: "kisisel",
    price: 3750,
    description: "Büyük hayal kuranlar için büyük bir ışık. Çalışma odası, ofis.",
    longDescription: "Motivasyonunuzu her gün tazelemek için harika bir dekor parçası. Çalışma odanıza, ev ofisinize veya yatak odanıza koyabileceğiniz 'Dream Big' tabelası, hedeflerinizi hatırlatırken mekanınızı güzelleştirir.",
    features: ["İnspirasyonel tasarım", "Çalışma odası uyumlu", "Yumuşak ışık efekti", "Düşük ses çıkaran güç adaptörü"],
    colors: [
      { name: "Mor", hex: "#9B5CFF" },
      { name: "Neon Mavi", hex: "#00E5FF" },
      { name: "Beyaz", hex: "#FFFFFF" },
      { name: "Neon Yeşil", hex: "#39FF14" },
    ],
    sizes: PRODUCT_SIZES.slice(0, 4),
    tags: ["motivasyon", "ofis", "çalışma odası", "kişisel"],
    emoji: "💭",
    glowColor: "#9B5CFF",
    material: "LED Neon Flex + Akrilik Panel",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.6,
    reviewCount: 94,
    inStock: true,
    isNew: true,
  },
  {
    id: 9,
    slug: "gym-no-pain-no-gain",
    name: "No Pain No Gain",
    category: "Spor Salonu",
    categorySlug: "spor",
    price: 5200,
    description: "Spor salonunuzu motive edici bir atmosfere dönüştürün.",
    longDescription: "Fitness tutkunlarına ve spor salonu sahiplerine özel. 'No Pain No Gain' tabelası, antrenman esnasında motivasyonu tavan yaparken mekanınıza güçlü bir karakter katıyor. Her rep'te yanında olacak.",
    features: ["Yüksek kontrast görünüm", "Darbeye dayanıklı montaj", "Nem ve ter dayanımlı", "Aydınlatma seçenekleri"],
    colors: [
      { name: "Mor", hex: "#9B5CFF" },
      { name: "Kırmızı", hex: "#FF3131" },
      { name: "Neon Yeşil", hex: "#39FF14" },
      { name: "Beyaz", hex: "#FFFFFF" },
    ],
    sizes: PRODUCT_SIZES,
    tags: ["spor", "gym", "fitness", "motivasyon"],
    badge: "Çok Satan",
    emoji: "💪",
    glowColor: "#9B5CFF",
    material: "LED Neon Flex + Siyah Akrilik Panel",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.8,
    reviewCount: 142,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 10,
    slug: "home-sweet-home",
    name: "Home Sweet Home",
    category: "Ev Dekorasyon",
    categorySlug: "ev",
    price: 4400,
    description: "Evinize sıcaklık katın. Oturma odası, mutfak, koridor.",
    longDescription: "İngilizce 'Home Sweet Home' (Ev Tatlı Ev) tabelası, evinizin en samimi köşesini oluşturur. Misafirlerinizi karşılar, aile fotoğraflarınızla mükemmel uyum sağlar ve evinize hem modern hem de nostaljik bir dokunuş katar.",
    features: ["Aile dostu tasarım", "Ahşap panel seçeneği", "Düşük enerji tüketimi", "Uzun ömürlü LED"],
    colors: [
      { name: "Neon Mavi", hex: "#00E5FF" },
      { name: "Turuncu", hex: "#FF7A00" },
      { name: "Neon Yeşil", hex: "#39FF14" },
      { name: "Beyaz", hex: "#FFFFFF" },
    ],
    sizes: PRODUCT_SIZES,
    tags: ["ev", "dekorasyon", "oturma odası", "hediye"],
    emoji: "🏠",
    glowColor: "#00E5FF",
    material: "LED Neon Flex + Ahşap/Akrilik Panel",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.7,
    reviewCount: 119,
    inStock: true,
  },
  {
    id: 11,
    slug: "happy-birthday",
    name: "Happy Birthday 🎂",
    category: "Özel Günler",
    categorySlug: "ozel-gun",
    price: 3500,
    description: "Doğum günü kutlamalarına ışıklı bir dokunuş. Kiralık veya satın al.",
    longDescription: "Doğum günü partilerinizi unutulmaz kılın! 'Happy Birthday' neon tabelamız, doğum günü fotoğraflarınızı sosyal medyada öne çıkaracak. Parti organizasyon firmalarının en çok tercih ettiği ürün.",
    features: ["Parti dekorasyonu", "Kolayca taşınabilir", "Şarjlı versiyon seçeneği", "Kiralık seçenek"],
    colors: [
      { name: "Neon Pembe", hex: "#FF00C8" },
      { name: "Altın", hex: "#FFD700" },
      { name: "Mor", hex: "#9B5CFF" },
      { name: "Turuncu", hex: "#FF7A00" },
    ],
    sizes: PRODUCT_SIZES.slice(0, 4),
    tags: ["doğum günü", "parti", "kutlama", "hediye"],
    badge: "Yeni",
    emoji: "🎉",
    glowColor: "#FF00C8",
    material: "LED Neon Flex + Taşınabilir Stand",
    warranty: "2 Yıl",
    deliveryDays: "5-7 iş günü",
    rating: 4.9,
    reviewCount: 87,
    inStock: true,
    isNew: true,
  },
  {
    id: 12,
    slug: "beauty-studio",
    name: "Beauty Studio",
    category: "Güzellik & Kuaför",
    categorySlug: "guzellik",
    price: 5100,
    description: "Güzellik stüdyonuzun kimliğini ışıkla ifade edin.",
    longDescription: "Profesyonel güzellik stüdyoları için tasarlanmış bu neon tabela, salonunuzun markasını güçlendirir. Makyaj alanları, nail art stüdyoları ve epilasyon merkezlerinde sıkça tercih edilmektedir.",
    features: ["Profesyonel görünüm", "Özelleştirilebilir yazı", "Studio aydınlatması", "Selfie köşesi"],
    colors: [
      { name: "Neon Pembe", hex: "#FF00C8" },
      { name: "Altın", hex: "#FFD700" },
      { name: "Mor", hex: "#9B5CFF" },
      { name: "Beyaz", hex: "#FFFFFF" },
    ],
    sizes: PRODUCT_SIZES,
    tags: ["güzellik", "studio", "salon", "makyaj"],
    emoji: "💄",
    glowColor: "#FF00C8",
    material: "LED Neon Flex + Akrilik Panel",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.8,
    reviewCount: 103,
    inStock: true,
  },
  {
    id: 13,
    slug: "barber-shop",
    name: "Barber Shop",
    category: "İşletme",
    categorySlug: "isletme",
    price: 4650,
    description: "Berber dükkanınızı şık bir neon tabela ile tamamlayın.",
    longDescription: "Geleneksel berber estetığini modern neon ışıklarla harmanlayan bu tabela, dükkanınıza nostaljik ve premium bir karakter katar. Makas ve tıraş temaları içeren tasarımlarla da özelleştirilebilir.",
    features: ["Berber teması", "Nostaljik tasarım", "Cam & Vitrin uyumlu", "Harfler özelleştirilebilir"],
    colors: [
      { name: "Neon Mavi", hex: "#00E5FF" },
      { name: "Kırmızı", hex: "#FF3131" },
      { name: "Beyaz", hex: "#FFFFFF" },
      { name: "Turuncu", hex: "#FF7A00" },
    ],
    sizes: PRODUCT_SIZES,
    tags: ["berber", "saç", "erkek", "işletme"],
    emoji: "✂️",
    glowColor: "#00E5FF",
    material: "LED Neon Flex + Akrilik Panel",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.7,
    reviewCount: 76,
    inStock: true,
  },
  {
    id: 14,
    slug: "iyi-geceler",
    name: "İyi Geceler ✨",
    category: "Ev Dekorasyon",
    categorySlug: "ev",
    price: 3800,
    description: "Yatak odanıza büyülü bir gece havası katın.",
    longDescription: "Yatak odanızın başucu lambası olarak ya da arka plan aydınlatması olarak kullanabileceğiniz 'İyi Geceler' tabelası, uyku öncesi rahatlatıcı bir atmosfer yaratır. Çocuk odaları ve genç odaları için de idealdir.",
    features: ["Gece lambası modu", "Dimmer ile karartma", "Uyku dostu sıcak ton", "Sessiz transformatör"],
    colors: [
      { name: "Mor", hex: "#9B5CFF" },
      { name: "Neon Pembe", hex: "#FF00C8" },
      { name: "Neon Mavi", hex: "#00E5FF" },
      { name: "Beyaz Sıcak", hex: "#FFF5E0" },
    ],
    sizes: PRODUCT_SIZES.slice(0, 4),
    tags: ["yatak odası", "gece", "uyku", "huzur"],
    emoji: "🌙",
    glowColor: "#9B5CFF",
    material: "LED Neon Flex + Akrilik Panel",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.8,
    reviewCount: 131,
    inStock: true,
  },
  {
    id: 15,
    slug: "neon-masa-lambasi",
    name: "Neon Masa Lambası",
    category: "Ev Dekorasyon",
    categorySlug: "ev",
    price: 2900,
    description: "Masanızın üzerinde duran kişiselleştirilebilir neon gece lambası.",
    longDescription: "Fişe takıp çalışma masanızın, komodininizin ya da raflığınızın üzerine yerleştirebileceğiniz kompakt neon masa lambası. USB destekli adaptörü ile dizüstü bilgisayarınıza veya şarj cihazınıza bağlanabilir.",
    features: ["USB powered", "360° döndürülebilir stand", "3 parlaklık seviyesi", "Kompakt boyut"],
    colors: [
      { name: "Neon Pembe", hex: "#FF00C8" },
      { name: "Neon Mavi", hex: "#00E5FF" },
      { name: "Mor", hex: "#9B5CFF" },
      { name: "Neon Yeşil", hex: "#39FF14" },
    ],
    sizes: [
      { key: "s", label: "S", cm: "15cm", priceAdd: 0 },
      { key: "m", label: "M", cm: "25cm", priceAdd: 500 },
      { key: "l", label: "L", cm: "35cm", priceAdd: 1200 },
    ],
    tags: ["masa lambası", "usb", "kompakt", "hediye"],
    badge: "Yeni",
    emoji: "💡",
    glowColor: "#FF7A00",
    material: "LED Neon Flex + Metal Stand",
    warranty: "1 Yıl",
    deliveryDays: "5-7 iş günü",
    rating: 4.6,
    reviewCount: 58,
    inStock: true,
    isNew: true,
  },
  {
    id: 16,
    slug: "restoran-hosgeldiniz",
    name: "Restorana Hoşgeldiniz",
    category: "Restoran",
    categorySlug: "restoran",
    price: 6200,
    description: "Restoranınızın atmosferini neon ışıklarla tamamlayın.",
    longDescription: "Fine dining veya casual restoranlar için özel tasarım neon tabela. Giriş, bar alanı veya duvar dekorasyonu olarak kullanılabilir. Restoranınızın markasına özel yazılar ve tasarımlar da mümkündür.",
    features: ["Restoran atmosferi", "Bar alanı uyumlu", "Özel tasarım seçeneği", "Gıda güvenli malzeme"],
    colors: [
      { name: "Turuncu", hex: "#FF7A00" },
      { name: "Kırmızı", hex: "#FF3131" },
      { name: "Altın", hex: "#FFD700" },
      { name: "Beyaz", hex: "#FFFFFF" },
    ],
    sizes: PRODUCT_SIZES,
    tags: ["restoran", "yemek", "bar", "atmosfer"],
    emoji: "🍽️",
    glowColor: "#FF7A00",
    material: "LED Neon Flex + Akrilik/Ahşap Panel",
    warranty: "2 Yıl",
    deliveryDays: "7-10 iş günü",
    rating: 4.9,
    reviewCount: 92,
    inStock: true,
  },
];

export const CATEGORIES_LIST = [
  { slug: "tumu", label: "Tümü", emoji: "✦" },
  { slug: "isletme", label: "İşletme", emoji: "🏢" },
  { slug: "kafe", label: "Kafe", emoji: "☕" },
  { slug: "restoran", label: "Restoran", emoji: "🍽️" },
  { slug: "guzellik", label: "Güzellik", emoji: "💄" },
  { slug: "spor", label: "Spor", emoji: "💪" },
  { slug: "ev", label: "Ev Dekorasyon", emoji: "🏠" },
  { slug: "ozel-gun", label: "Özel Günler", emoji: "🎉" },
  { slug: "kisisel", label: "Kişisel", emoji: "✨" },
];

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug) ?? null;
}

export function getRelatedProducts(product: Product, limit = 4) {
  return PRODUCTS.filter(
    (p) => p.categorySlug === product.categorySlug && p.id !== product.id
  ).slice(0, limit);
}

export function getBestSellers() {
  return PRODUCTS.filter((p) => p.isBestSeller);
}

export function getNewProducts() {
  return PRODUCTS.filter((p) => p.isNew);
}
