export interface PromoProduct {
  slug: string;
  name: string;
  description: string;
  features: string[];
  minQty: number;
  image: string;
}

export interface PromoCategory {
  slug: string;
  title: string;
  desc: string;
  icon: string; // lucide icon adı
  image: string;
  color: string;
  products: PromoProduct[];
}

export const PROMO_CATEGORIES: PromoCategory[] = [
  {
    slug: "ajanda-ve-defterler",
    title: "Ajanda ve Defterler",
    desc: "Kurumsal logolu günlük ajandalar ve defterler; termo deri veya PU kapaklı, çok sayıda baskı seçeneğiyle.",
    icon: "Notebook",
    image: "/promosyon/312/ajanda-ve-defterler/_category.jpg",
    color: "#5FAE7F",
    products: [
      {
        slug: "catalca-t-gunluk-ajanda",
        name: "Çatalca-T Günlük Ajanda",
        description: "Termo PU sert kapaklı günlük ajanda; 320 sayfa krem kağıt ile kurumsal kullanım için tasarlandı.",
        features: ["Termo PU sert kapak", "Gofre / dijital baskı", "320 sayfa, 70 gr krem kağıt", "16x24 cm"],
        minQty: 50,
        image: "/promosyon/312/ajanda-ve-defterler/catalca-t-gunluk-ajanda.jpg",
      },
      {
        slug: "uskudar-k-gunluk-ajanda",
        name: "Üsküdar-K Günlük Ajanda",
        description: "Termo deri kapaklı, kalem yuvalı günlük ajanda; 336 sayfa krem kağıt ile 17x24 cm ölçülerinde.",
        features: ["Termo deri kapak", "Kalem yuvası", "Gofre / serigrafi / UV baskı", "336 sayfa, 70 gr kağıt"],
        minQty: 50,
        image: "/promosyon/312/ajanda-ve-defterler/uskudar-k-gunluk-ajanda.jpg",
      },
      {
        slug: "eminonu-tb-gunluk-ajanda",
        name: "Eminönü-TB Günlük Ajanda",
        description: "Kalem yuvalı, termo PU sert kapaklı günlük ajanda; 336 sayfa fildişi krem kağıt, 17x24 cm.",
        features: ["Termo PU sert kapak", "Kalem yuvası", "Gofre / serigrafi / dijital baskı", "336 sayfa, 70 gr kağıt"],
        minQty: 50,
        image: "/promosyon/312/ajanda-ve-defterler/eminonu-tb-gunluk-ajanda.jpg",
      },
      {
        slug: "hereke-s-gizli-spiralli-ajanda",
        name: "Hereke-S Gizli Spiralli Ajanda",
        description: "Gizli spiral ciltli, termo PU sert kapaklı siyah ajanda; 336 sayfa krem kağıt, 17,5x24 cm.",
        features: ["Gizli spiral cilt", "Termo PU sert kapak", "Dijital / serigrafi / gofre baskı", "336 sayfa, 70 gr kağıt"],
        minQty: 50,
        image: "/promosyon/312/ajanda-ve-defterler/hereke-s-gizli-spiralli-ajanda.jpg",
      },
    ],
  },
  {
    slug: "kalemler",
    title: "Kalemler",
    desc: "Metal gövdeli tükenmez ve roller kalemler; lazer kazıma veya tampon baskı ile logonuz kalıcı olsun.",
    icon: "Pen",
    image: "/promosyon/312/kalemler/_category.jpg",
    color: "#D9668A",
    products: [
      {
        slug: "metal-tukenmez-kalem-krom",
        name: "Metal Tükenmez Kalem (Krom)",
        description: "İnce uçlu, krom kaplamalı metal gövdeli tükenmez kalem; çok sayıda renk seçeneğiyle üretilebilir.",
        features: ["Metal gövde", "İnce uç", "Krom / siyah / kırmızı renk seçenekleri", "Lazer kazıma veya tampon baskı"],
        minQty: 100,
        image: "/promosyon/312/kalemler/metal-tukenmez-kalem-krom.jpg",
      },
      {
        slug: "metal-tukenmez-kalem-fistik-yesili",
        name: "Metal Tükenmez Kalem (Fıstık Yeşili)",
        description: "Dokunmatik uçlu, ince yazan metal gövdeli tükenmez kalem; birçok renk alternatifiyle sunulur.",
        features: ["Dokunmatik uç", "Metal gövde", "İnce uç mekanizması", "Çok renk seçeneği"],
        minQty: 100,
        image: "/promosyon/312/kalemler/metal-tukenmez-kalem-fistik-yesili.jpg",
      },
      {
        slug: "metal-roller-kalem-elma-yesili",
        name: "Metal Roller Kalem (Elma Yeşili)",
        description: "Kurumsal hediye setlerine uygun, elma yeşili renkte metal gövdeli roller kalem.",
        features: ["Metal gövde", "Roller mekanizma", "Lazer kazıma baskı", "Kurumsal renk seçenekleri"],
        minQty: 100,
        image: "/promosyon/312/kalemler/metal-roller-kalem-elma-yesili.jpg",
      },
      {
        slug: "metal-tukenmez-kalem-turuncu",
        name: "Metal Tükenmez Kalem (Turuncu)",
        description: "Dayanıklı metal gövdeli, turuncu renkli tükenmez kalem; farklı renk seçenekleriyle de üretilir.",
        features: ["Metal gövde", "Tükenmez kalem mekanizması", "Turuncu / turkuaz / siyah / kırmızı seçenekleri", "Lazer kazıma baskı"],
        minQty: 100,
        image: "/promosyon/312/kalemler/metal-tukenmez-kalem-turuncu.jpg",
      },
    ],
  },
  {
    slug: "termoslar-ve-bardaklar",
    title: "Termoslar ve Bardaklar",
    desc: "Çift cidarlı çelik termoslar, matara ve termos bardaklar; lazer veya UV baskı ile logonuz taşınsın.",
    icon: "CupSoda",
    image: "/promosyon/312/termoslar-ve-bardaklar/_category.jpg",
    color: "#F2B84B",
    products: [
      {
        slug: "devrilmez-termos-500ml",
        name: "Devrilmez Termos 500 ml",
        description: "500 ml kapasiteli, devrilmeye karşı dayanıklı tasarımlı yalıtımlı termos; lazer ve UV baskıya uygundur.",
        features: ["500 ml kapasite", "Devrilmez taban tasarımı", "Lazer / UV baskı", "Yalıtımlı çift cidar"],
        minQty: 25,
        image: "/promosyon/312/termoslar-ve-bardaklar/devrilmez-termos-500ml.jpg",
      },
      {
        slug: "metalik-termos-750ml",
        name: "Metalik Termos 750 ml (Deri Kılıflı)",
        description: "750 ml kapasiteli, deri kılıflı metalik termos; lazer baskı ile kurumsal logo uygulanır.",
        features: ["750 ml kapasite", "Deri taşıma kılıfı", "Metalik gövde", "Lazer baskı"],
        minQty: 25,
        image: "/promosyon/312/termoslar-ve-bardaklar/metalik-termos-750ml.jpg",
      },
      {
        slug: "paslanmaz-celik-matara-700ml",
        name: "Paslanmaz Çelik Matara 700 ml",
        description: "700 ml kapasiteli paslanmaz çelik matara; günlük kullanım ve promosyon dağıtımları için uygundur.",
        features: ["Paslanmaz çelik gövde", "700 ml kapasite", "Lazer baskı", "Beyaz / kırmızı / lacivert / siyah / gümüş renk seçenekleri"],
        minQty: 25,
        image: "/promosyon/312/termoslar-ve-bardaklar/paslanmaz-celik-matara-700ml.jpg",
      },
      {
        slug: "bardak-termos-240ml",
        name: "Bardak Termos 240 ml",
        description: "240 ml kapasiteli kompakt termos bardak; lacivert, beyaz ve füme renk seçenekleriyle sunulur.",
        features: ["240 ml kapasite", "Tampon baskı", "Lacivert / beyaz / füme renk seçenekleri", "Kompakt boyut"],
        minQty: 50,
        image: "/promosyon/312/termoslar-ve-bardaklar/bardak-termos-240ml.jpg",
      },
    ],
  },
  {
    slug: "kupa-ve-plaketler",
    title: "Kupa ve Plaketler",
    desc: "Ödül kupaları ve madalyalar; kurumsal ödül törenleri ve spor organizasyonları için şık çözümler.",
    icon: "Trophy",
    image: "/promosyon/312/kupa-ve-plaketler/_category.jpg",
    color: "#FF8F66",
    products: [
      {
        slug: "oscar-odul-kupasi",
        name: "Oscar Ödül Kupası",
        description: "9x28 cm ölçülerinde, Oscar stilinde tasarlanmış ödül kupası; başarı ve teşekkür ödüllerinde kullanılır.",
        features: ["Oscar tarzı tasarım", "9x28 cm ölçü", "Gravür / lazer baskı ile kişiselleştirme"],
        minQty: 25,
        image: "/promosyon/312/kupa-ve-plaketler/oscar-odul-kupasi.jpg",
      },
      {
        slug: "bronz-madalya",
        name: "Bronz Madalya",
        description: "5,5 cm çapında bronz renkli madalya; yarışma ve ödül törenleri için idealdir.",
        features: ["Bronz kaplama", "Ø 5,5 cm çap", "Kurdele ile birlikte sunulur", "Gravür / baskı ile logo uygulanır"],
        minQty: 25,
        image: "/promosyon/312/kupa-ve-plaketler/bronz-madalya.jpg",
      },
      {
        slug: "gumus-madalya-5cm",
        name: "Gümüş Madalya (5 cm)",
        description: "5 cm çapında gümüş renkli madalya; ödül ve yarışma organizasyonlarında kullanılır.",
        features: ["Gümüş kaplama", "Ø 5 cm çap", "Kurdeleli sunum", "Gravür ile logo / yazı işleme"],
        minQty: 25,
        image: "/promosyon/312/kupa-ve-plaketler/gumus-madalya-5cm.jpg",
      },
      {
        slug: "gumus-madalya-7cm",
        name: "Gümüş Madalya (7 cm)",
        description: "7 cm çapında, daha büyük ölçekli gümüş renkli madalya; kurumsal ödül törenleri için.",
        features: ["Gümüş renk", "Ø 7 cm çap", "Kurdeleli sunum", "Gravür ile kişiselleştirme"],
        minQty: 25,
        image: "/promosyon/312/kupa-ve-plaketler/gumus-madalya-7cm.jpg",
      },
    ],
  },
  {
    slug: "saatler",
    title: "Saatler",
    desc: "Metal gövdeli duvar saatleri; ofis, mağaza ve kurumsal alanlar için logolu tasarım seçenekleri.",
    icon: "Watch",
    image: "/promosyon/312/saatler/_category.jpg",
    color: "#5FAE7F",
    products: [
      {
        slug: "metal-duvar-saati-30cm",
        name: "Metal Duvar Saati (30 cm)",
        description: "30 cm çapında paslanmaz metal gövdeli duvar saati; mineral cam kadran ve akar saniye mekanizmasıyla.",
        features: ["Paslanmaz çelik gövde", "Mineral cam kadran", "Akar saniye mekanizması", "Ø 30 cm"],
        minQty: 25,
        image: "/promosyon/312/saatler/metal-duvar-saati-30cm.jpg",
      },
      {
        slug: "metal-duvar-saati-40cm",
        name: "Metal Duvar Saati (40 cm)",
        description: "40 cm çapında büyük boy paslanmaz çelik duvar saati; mineral cam ve akar saniye mekanizması içerir.",
        features: ["Paslanmaz çelik gövde", "Mineral cam", "Akar saniye mekanizması", "Ø 40 cm"],
        minQty: 25,
        image: "/promosyon/312/saatler/metal-duvar-saati-40cm.jpg",
      },
      {
        slug: "metal-duvar-saati-25cm",
        name: "Metal Duvar Saati (25 cm)",
        description: "25 cm çapında kompakt paslanmaz çelik duvar saati; ofis ve mağaza kullanımına uygundur.",
        features: ["Paslanmaz çelik gövde", "Mineral cam kadran", "Akar saniye mekanizması", "Ø 25 cm"],
        minQty: 25,
        image: "/promosyon/312/saatler/metal-duvar-saati-25cm.jpg",
      },
      {
        slug: "metal-duvar-saati-31cm",
        name: "Metal Duvar Saati (31 cm)",
        description: "31 cm çapında paslanmaz çelik duvar saati; mineral cam ve akar saniye mekanizmasıyla üretilir.",
        features: ["Paslanmaz çelik gövde", "Mineral cam kadran", "Akar saniye mekanizması", "Ø 31 cm"],
        minQty: 25,
        image: "/promosyon/312/saatler/metal-duvar-saati-31cm.png",
      },
    ],
  },
  {
    slug: "kagit-urunleri",
    title: "Kağıt Ürünleri",
    desc: "Masa takvimleri ve kağıt promosyon ürünleri; kurumsal tasarımla yıl boyu markanızı hatırlatır.",
    icon: "FileText",
    image: "/promosyon/312/kagit-urunleri/_category.png",
    color: "#D9668A",
    products: [
      {
        slug: "selale-masa-takvimi",
        name: "Şelale Masa Takvimi",
        description: "Beyaz renkli, 20x14 cm ölçülerinde şelale tipi masa takvimi; 170 gr parlak kuşe kağıttan 13 yapraklı.",
        features: ["400 gr bristol taşıyıcı", "13 yaprak, 170 gr parlak kuşe", "20x14 cm", "Şelale tipi katlama"],
        minQty: 100,
        image: "/promosyon/312/kagit-urunleri/selale-masa-takvimi.png",
      },
      {
        slug: "anadolu-masa-takvimi-beyaz",
        name: "Anadolu Masa Takvimi (Beyaz)",
        description: "Dokulu beyaz taşıyıcılı, Anadolu desenli masa takvimi; 20x14x7 cm ölçülerinde ayaklı standı ile.",
        features: ["400 gr dokulu bristol taşıyıcı", "13 yaprak, 170 gr parlak kağıt", "20x14x7 cm", "Ayaklı masa standı"],
        minQty: 100,
        image: "/promosyon/312/kagit-urunleri/anadolu-masa-takvimi-beyaz.jpg",
      },
      {
        slug: "osmanli-masa-takvimi",
        name: "Osmanlı Masa Takvimi",
        description: "Osmanlı motifli, siyah-beyaz tasarımlı masa takvimi; 20x14x7 cm ölçülerinde 13 yapraklı.",
        features: ["400 gr bristol taşıyıcı", "13 yaprak, 170 gr parlak kağıt", "20x14x7 cm", "Osmanlı desenli tasarım"],
        minQty: 100,
        image: "/promosyon/312/kagit-urunleri/osmanli-masa-takvimi.jpg",
      },
      {
        slug: "karton-tasiyicili-masa-takvimi",
        name: "Karton Taşıyıcılı Masa Takvimi",
        description: "Karton taşıyıcılı, farklı ebat ve kağıt ağırlığı seçenekleriyle özelleştirilebilir masa takvimi.",
        features: ["400 gr bristol veya kraft taşıyıcı", "170-300 gr kuşe kağıt seçenekleri", "Farklı ebat seçenekleri (17x15, 20x14 cm vb.)", "Kurumsal logo baskısı"],
        minQty: 100,
        image: "/promosyon/312/kagit-urunleri/karton-tasiyicili-masa-takvimi.jpg",
      },
    ],
  },
  {
    slug: "cantalar",
    title: "Çantalar",
    desc: "Ham bez ve elyaf çantalar; serigrafi veya DTF baskı ile sürdürülebilir marka imajı oluşturun.",
    icon: "ShoppingBag",
    image: "/promosyon/312/cantalar/_category.jpg",
    color: "#F2B84B",
    products: [
      {
        slug: "ham-bez-canta",
        name: "Ham Bez Çanta",
        description: "Günlük kullanıma uygun, tek gözlü ham bez çanta; DTF baskı ile logonuz canlı renklerde işlenir.",
        features: ["Ham bez malzeme", "Tek göz tasarım", "Elde veya omuzda taşıma sapı", "DTF baskı uyumlu"],
        minQty: 100,
        image: "/promosyon/312/cantalar/ham-bez-canta.jpg",
      },
      {
        slug: "ip-buzgulu-ham-bez-canta-sirt",
        name: "İp Büzgülü Ham Bez Çanta (Sırt Tipi)",
        description: "İp büzgülü, sırt çantası olarak da kullanılabilen doğa dostu ham bez çanta; yerli üretimdir.",
        features: ["İp büzgülü kapanış", "Serigrafi / DTF baskı", "Sırt çantası kullanımına uygun", "Doğa dostu, yerli üretim"],
        minQty: 100,
        image: "/promosyon/312/cantalar/ip-buzgulu-ham-bez-canta-sirt.jpg",
      },
      {
        slug: "ip-buzgulu-ham-bez-canta-iki-yonlu",
        name: "İp Büzgülü Ham Bez Çanta (İki Yönlü)",
        description: "İki yönlü büzgülü ham bez çanta; hem sırt çantası hem omuz çantası olarak kullanılabilir.",
        features: ["Ham bez malzeme", "İki yönlü büzgü kapanış", "Taşıma ipi", "DTF / serigrafi / transfer baskı"],
        minQty: 100,
        image: "/promosyon/312/cantalar/ip-buzgulu-ham-bez-canta-iki-yonlu.jpg",
      },
      {
        slug: "elyaf-canta",
        name: "Elyaf Çanta",
        description: "Üç farklı ebat seçeneğiyle sunulan promosyon elyaf çanta; özel renk kombinasyonlarıyla üretilebilir.",
        features: ["Elyaf malzeme", "25x35 / 30x40 / 35x45 cm ebat seçenekleri", "Özel renk kombinasyonu imkanı"],
        minQty: 100,
        image: "/promosyon/312/cantalar/elyaf-canta.png",
      },
    ],
  },
  {
    slug: "teknolojik-urunler",
    title: "Teknolojik Ürünler",
    desc: "USB bellekler ve teknoloji aksesuarları; metal, deri ve kristal gövde seçenekleriyle logonuzu taşıyın.",
    icon: "Cpu",
    image: "/promosyon/312/teknolojik-urunler/_category.jpg",
    color: "#FF8F66",
    products: [
      {
        slug: "kristal-usb-bellek-16gb",
        name: "Kristal USB Bellek 16 GB",
        description: "Metal ve kristal gövdeli, ışıklandırma özellikli 16 GB USB bellek.",
        features: ["16 GB kapasite", "Metal + kristal gövde", "Işıklandırma özelliği", "Lazer kazıma logo"],
        minQty: 50,
        image: "/promosyon/312/teknolojik-urunler/kristal-usb-bellek-16gb.jpg",
      },
      {
        slug: "deri-usb-bellek-16gb",
        name: "Deri USB Bellek 16 GB",
        description: "Deri kaplamalı, metal gövdeli 16 GB USB bellek; şık ve kurumsal bir görünüm sunar.",
        features: ["16 GB kapasite", "Deri kaplama + metal gövde", "Lazer kazıma logo"],
        minQty: 50,
        image: "/promosyon/312/teknolojik-urunler/deri-usb-bellek-16gb.jpg",
      },
      {
        slug: "metal-usb-bellek-16gb",
        name: "Metal USB Bellek 16 GB",
        description: "Sade metal gövdeli 16 GB USB bellek; kurumsal hediye ve fuar dağıtımları için uygundur.",
        features: ["16 GB kapasite", "Metal gövde", "Lazer kazıma logo"],
        minQty: 50,
        image: "/promosyon/312/teknolojik-urunler/metal-usb-bellek-16gb.jpg",
      },
      {
        slug: "usb-kalem-seti-16gb",
        name: "USB Kalem Seti 16 GB",
        description: "Metal gövdeli, 16 GB USB bellek özellikli kalem seti; lacivert, beyaz, kırmızı ve siyah renk seçenekleriyle.",
        features: ["16 GB USB bellek + kalem bir arada", "Metal gövde", "Lacivert / beyaz / kırmızı / siyah renk seçenekleri"],
        minQty: 50,
        image: "/promosyon/312/teknolojik-urunler/usb-kalem-seti-16gb.jpg",
      },
    ],
  },
  {
    slug: "dogadostu-urunler",
    title: "Doğadostu Ürünler",
    desc: "Geri dönüşümlü kağıttan üretilen notluk ve defterler; sürdürülebilir marka mesajınız için.",
    icon: "Leaf",
    image: "/promosyon/312/dogadostu-urunler/_category.jpg",
    color: "#5FAE7F",
    products: [
      {
        slug: "yapiskanli-notluk-kalemlikli",
        name: "Kalemlikli Yapışkanlı Notluk",
        description: "Geri dönüşümlü kraft kağıttan üretilen, kalem yuvalı yapışkanlı notluk; 14x10,7 cm ölçülerinde.",
        features: ["Geri dönüşümlü kraft kağıt", "Kalem yuvası (kalem dahil değil)", "Serigrafi / dijital baskı", "14x10,7 cm"],
        minQty: 100,
        image: "/promosyon/312/dogadostu-urunler/yapiskanli-notluk-kalemlikli.jpg",
      },
      {
        slug: "spiralli-defter-geri-donusumlu",
        name: "Spiralli Defter (Geri Dönüşümlü)",
        description: "Sert kapaklı, krem sayfalı spiralli defter; kalem yuvası ve yapışkanlı not kağıdı içerir.",
        features: ["Sert kapak", "70 gr krem kağıt, 55 yaprak", "Kalem yuvası + yapışkanlı not kağıdı", "Serigrafi / dijital baskı"],
        minQty: 100,
        image: "/promosyon/312/dogadostu-urunler/spiralli-defter-geri-donusumlu.jpg",
      },
      {
        slug: "deri-kapakli-yapiskanli-notluk",
        name: "Deri Kapaklı Yapışkanlı Notluk",
        description: "Suni deri kapaklı, 23x10,5x2 cm ölçülerinde yapışkanlı not tutucu.",
        features: ["Suni deri kapak", "23x10,5x2 cm", "Dijital / serigrafi baskı"],
        minQty: 100,
        image: "/promosyon/312/dogadostu-urunler/deri-kapakli-yapiskanli-notluk.jpg",
      },
      {
        slug: "spiralli-notluk-kraft-kapak",
        name: "Spiralli Notluk (Kraft Kapak)",
        description: "Kraft kapaklı, 150 çizgili sayfalı, kalem yuvalı spiralli notluk; geri dönüşümlü malzemeden üretilir.",
        features: ["Kraft (geri dönüşümlü) kapak", "150 çizgili sayfa, 70 gr kağıt", "Kalem yuvası + yapışkanlı not kağıdı", "UV / serigrafi baskı"],
        minQty: 100,
        image: "/promosyon/312/dogadostu-urunler/spiralli-notluk-kraft-kapak.jpg",
      },
    ],
  },
  {
    slug: "masa-setleri-ve-sumenleri",
    title: "Masa Setleri ve Sümenleri",
    desc: "Kalem, kartvizitlik ve sümenden oluşan masaüstü setleri; ofis masalarına şıklık katar.",
    icon: "LayoutGrid",
    image: "/promosyon/312/masa-setleri-ve-sumenleri/_category.jpg",
    color: "#D9668A",
    products: [
      {
        slug: "kristal-masa-sumeni-seti",
        name: "Kristal Masa Sümeni Seti",
        description: "Kalem seti, notluk, kalemlik, küp bloknot ve kartvizitlikten oluşan 5 parçalı masa seti; kahverengi deri kutuda sunulur.",
        features: ["5 parça masa seti", "Kalem seti + kartvizitlik + kalemlik", "Küp bloknot dahil", "Özel deri kutu"],
        minQty: 10,
        image: "/promosyon/312/masa-setleri-ve-sumenleri/kristal-masa-sumeni-seti.jpg",
      },
      {
        slug: "inci-masa-sumeni-seti",
        name: "İnci Masa Sümeni Seti",
        description: "Kalem seti, notluk, kalemlik, küp bloknot, kartvizitlik ve telefon standından oluşan 6 parçalı masa seti; siyah deri kutuda sunulur.",
        features: ["6 parça masa seti", "Telefon standı dahil", "Kartvizitlik + kalemlik", "Özel siyah deri kutu"],
        minQty: 10,
        image: "/promosyon/312/masa-setleri-ve-sumenleri/inci-masa-sumeni-seti.jpg",
      },
      {
        slug: "mercan-masa-seti",
        name: "Mercan Masa Seti",
        description: "Kalem seti, telefon standı, küp bloknot, notluk, kalemlik ve kartvizitlikten oluşan 6 parçalı masa seti; deri kutuda sunulur.",
        features: ["6 parça masa seti", "Telefon standı dahil", "Kartvizitlik + kalemlik", "Özel deri kutu"],
        minQty: 10,
        image: "/promosyon/312/masa-setleri-ve-sumenleri/mercan-masa-seti.jpg",
      },
      {
        slug: "bayrak-masa-sumeni-seti",
        name: "Bayrak Masa Sümeni Seti",
        description: "Masa sümeni, kalem seti, kalemlik, notluk, dosyalık ve takvimlikten oluşan 6 parçalı masaüstü organizasyon seti.",
        features: ["6 parça set", "Masa sümeni + kalemlik + dosyalık", "Takvimlik dahil", "Kurumsal logo baskısı"],
        minQty: 10,
        image: "/promosyon/312/masa-setleri-ve-sumenleri/bayrak-masa-sumeni-seti.jpg",
      },
    ],
  },
  {
    slug: "tekstil-urunleri",
    title: "Tekstil Ürünleri",
    desc: "Tişört, yelek ve şapka gibi kurumsal tekstil ürünleri; baskı ve nakış seçenekleriyle.",
    icon: "Shirt",
    image: "/promosyon/312/tekstil-urunleri/_category.jpg",
    color: "#F2B84B",
    products: [
      {
        slug: "bisiklet-yaka-tisort",
        name: "Bisiklet Yaka Tişört",
        description: "%100 pamuk, 30/1 supreme kumaştan üretilen bisiklet yaka tişört; çok renk ve beden seçeneğiyle.",
        features: ["%100 pamuk, 30/1 supreme kumaş", "Bisiklet yaka", "Çok renk / beden seçeneği", "Baskıya uygun yüzey"],
        minQty: 50,
        image: "/promosyon/312/tekstil-urunleri/bisiklet-yaka-tisort.jpg",
      },
      {
        slug: "reflektorlu-yelek",
        name: "Reflektörlü Yelek",
        description: "%100 polyesterden üretilen, çift reflektörlü turuncu iş güvenliği yeleği; DTF baskı ile logo uygulanabilir.",
        features: ["%100 polyester", "Çift reflektör şerit", "Turuncu renk", "DTF baskı uyumlu"],
        minQty: 50,
        image: "/promosyon/312/tekstil-urunleri/reflektorlu-yelek.jpeg",
      },
      {
        slug: "polo-yaka-tisort",
        name: "Polo Yaka Tişört",
        description: "%100 pamuk lakos kumaştan üretilen polo yaka tişört; istenilen renk ve bedende toplu üretilebilir.",
        features: ["%100 pamuk lakos kumaş", "Polo yaka", "Talep edilen renk / beden seçeneği", "Kurumsal nakış veya baskı"],
        minQty: 50,
        image: "/promosyon/312/tekstil-urunleri/polo-yaka-tisort.jpg",
      },
      {
        slug: "v-yaka-tisort",
        name: "V Yaka Tişört",
        description: "%100 pamuk lakos kumaştan üretilen V yaka tişört; DTF baskıya uygun, istenilen renk ve bedende üretilir.",
        features: ["%100 pamuk lakos kumaş", "V yaka", "DTF baskı uyumlu", "İstenilen renk / beden seçeneği"],
        minQty: 50,
        image: "/promosyon/312/tekstil-urunleri/v-yaka-tisort.jpg",
      },
    ],
  },
  {
    slug: "kartvizitlikler",
    title: "Kartvizitlikler",
    desc: "Deri kartvizitlikler; metal detaylı ve farklı renk seçenekleriyle kurumsal sunumlarınızı tamamlar.",
    icon: "CreditCard",
    image: "/promosyon/312/kartvizitlikler/_category.jpg",
    color: "#FF8F66",
    products: [
      {
        slug: "siyah-deri-kartvizitlik",
        name: "Siyah Deri Kartvizitlik",
        description: "9,5x6 cm ölçülerinde, metal detaylı siyah deri kartvizitlik.",
        features: ["Deri malzeme", "Metal detay alanı", "9,5x6 cm", "Yatay kullanım"],
        minQty: 50,
        image: "/promosyon/312/kartvizitlikler/siyah-deri-kartvizitlik.jpg",
      },
      {
        slug: "deri-kartvizitlik-metal-detay",
        name: "Deri Kartvizitlik (Metal Detaylı)",
        description: "Metal detaylı, 9,5x6 cm ölçülerinde deri kartvizitlik.",
        features: ["Deri malzeme", "Metal detay alanı", "9,5x6 cm"],
        minQty: 50,
        image: "/promosyon/312/kartvizitlikler/deri-kartvizitlik-metal-detay.jpg",
      },
      {
        slug: "deri-dikey-kartvizitlik",
        name: "Deri Dikey Kartvizitlik",
        description: "6,5x9,4 cm ölçülerinde dikey formatlı deri kartvizitlik; metal detay alanı ile kişiselleştirilebilir.",
        features: ["Deri malzeme", "Dikey format", "Metal detay alanı", "6,5x9,4 cm"],
        minQty: 50,
        image: "/promosyon/312/kartvizitlikler/deri-dikey-kartvizitlik.jpg",
      },
      {
        slug: "kirmizi-termo-deri-kartvizitlik",
        name: "Kırmızı Termo Deri Kartvizitlik",
        description: "Termo deri malzemeden üretilen, metal detaylı kırmızı renkli kartvizitlik.",
        features: ["Termo deri malzeme", "Metal detay alanı", "Kompakt yatay format", "Kırmızı renk"],
        minQty: 50,
        image: "/promosyon/312/kartvizitlikler/kirmizi-termo-deri-kartvizitlik.jpg",
      },
    ],
  },
  {
    slug: "anahtarliklar",
    title: "Anahtarlıklar",
    desc: "Metal ve şeffaf anahtarlıklar; lazer kazıma veya çift taraflı baskı ile kişiye özel tasarım.",
    icon: "KeyRound",
    image: "/promosyon/312/anahtarliklar/_category.jpg",
    color: "#5FAE7F",
    products: [
      {
        slug: "lazer-kazima-anahtarlik",
        name: "Lazer Kazıma Anahtarlık",
        description: "68x39 mm ölçülerinde, tek yüzeyli lazer kazıma baskılı metal anahtarlık.",
        features: ["Tek yüzey baskı", "Lazer kazıma", "68x39 mm ölçü"],
        minQty: 100,
        image: "/promosyon/312/anahtarliklar/lazer-kazima-anahtarlik.jpg",
      },
      {
        slug: "cift-tarafli-renkli-anahtarlik",
        name: "Çift Taraflı Renkli Anahtarlık",
        description: "115x23 mm ölçülerinde, çift taraflı tasarımlı, çok renk seçenekli anahtarlık.",
        features: ["Çift taraflı tasarım", "Gofre veya lazer kazıma baskı", "115x23 mm ölçü", "Turuncu / siyah / lacivert / kırmızı / bej / turkuaz renk seçenekleri"],
        minQty: 100,
        image: "/promosyon/312/anahtarliklar/cift-tarafli-renkli-anahtarlik.jpg",
      },
      {
        slug: "siyah-cift-tarafli-anahtarlik",
        name: "Siyah Çift Taraflı Anahtarlık",
        description: "80x42 mm ölçülerinde, çift taraflı tasarımlı siyah anahtarlık; füme renk seçeneği de mevcuttur.",
        features: ["Çift taraflı tasarım", "Lazer baskı / kazıma", "80x42 mm ölçü", "Siyah / füme renk seçenekleri"],
        minQty: 100,
        image: "/promosyon/312/anahtarliklar/siyah-cift-tarafli-anahtarlik.jpg",
      },
      {
        slug: "seffaf-zincirsiz-anahtarlik",
        name: "Şeffaf Zincirsiz Anahtarlık",
        description: "Fotoğraf yerleştirmeye uygun, çift taraflı şeffaf anahtarlık; zincirsiz tasarımıyla kişisel hediyeler için idealdir.",
        features: ["Şeffaf malzeme", "Çift taraflı fotoğraf alanı", "Zincirsiz tasarım", "80x35 mm ölçü"],
        minQty: 100,
        image: "/promosyon/312/anahtarliklar/seffaf-zincirsiz-anahtarlik.jpg",
      },
    ],
  },
  {
    slug: "luks-hediyelik-setler",
    title: "Lüks Hediyelik Setler",
    desc: "Defter, kalem, powerbank ve termos gibi ürünlerden oluşan özel kutulu hediye setleri.",
    icon: "Gift",
    image: "/promosyon/312/luks-hediyelik-setler/_category.jpg",
    color: "#D9668A",
    products: [
      {
        slug: "ardahan-hediyelik-set",
        name: "Ardahan Hediyelik Set",
        description: "35x29x14 cm ölçülerinde özel kutulu hediye seti; deri defter, cam matara, bluetooth hoparlör ve 16 GB USB bellek içerir.",
        features: ["Deri defter (14,5x21 cm)", "Cam matara", "Bluetooth hoparlör", "16 GB USB bellek", "Özel hediye kutusu"],
        minQty: 10,
        image: "/promosyon/312/luks-hediyelik-setler/ardahan-hediyelik-set.jpg",
      },
      {
        slug: "denizli-hediyelik-set",
        name: "Denizli Hediyelik Set",
        description: "35x29x14 cm ölçülerinde, teknoloji ve yaşam tarzı ürünlerini bir araya getiren hediye seti; hoparlör, termos ve powerbank içerir.",
        features: ["Bluetooth hoparlör", "500 ml French press termos", "Powerbank", "Özel hediye kutusu"],
        minQty: 10,
        image: "/promosyon/312/luks-hediyelik-setler/denizli-hediyelik-set.png",
      },
      {
        slug: "ayvalik-hediyelik-set",
        name: "Ayvalık Hediyelik Set",
        description: "28,5x26x3,5 cm ölçülerinde hediye seti; termo deri defter, powerbank, metal roller kalem, anahtarlık ve USB bellek içerir.",
        features: ["Termo deri defter (9,5x14 cm)", "Powerbank", "Metal roller kalem", "Metal + deri anahtarlık", "16 GB USB bellek", "Özel hediye kutusu"],
        minQty: 10,
        image: "/promosyon/312/luks-hediyelik-setler/ayvalik-hediyelik-set.jpg",
      },
      {
        slug: "antep-g-hediyelik-set",
        name: "Antep-G Hediyelik Set",
        description: "25x19x4 cm ölçülerinde gri renkli hediye seti; termo deri defter ve metal tükenmez kalemden oluşur.",
        features: ["Termo deri defter (13x21 cm)", "Metal tükenmez kalem", "Özel hediye kutusu"],
        minQty: 10,
        image: "/promosyon/312/luks-hediyelik-setler/antep-g-hediyelik-set.jpg",
      },
    ],
  },
];

export function getPromoCategory(slug: string) {
  return PROMO_CATEGORIES.find((c) => c.slug === slug) ?? null;
}
